#!/usr/bin/env python3

import bt_helper

def main():
    mgr = bt_helper.BtManager()
    mgr.ensure_adapters_powered()
    mgr.scan()

    devs = list(mgr.get_bt_devices(filters={'Address': 'C2:A5:FD:E5:9B:AA'}))
    if not devs:
        print('no devices found!')
    for dev in devs:
        dev.pair()
        print('finished pairing.')

if __name__ == '__main__':
    main()
